### ISSUE TITLE
Provide binary builds

### ISSUE THREAD

**Issue by tfedyanin** [Pshatsillo/openhab2MegadBinding#2]
Достаточно неудобно бороться каждый раз с настройкой всей инфраструктуры под OH2 чтобы получить бинарную сборку.
Было бы замечательно иметь возможность скачать собранный артифакт из bintray или даже из папки target.

Ну или хотя бы добавить инструкцию по сборке в README.md:

- Склонировать  проект в папку openhab2-addons/addons/binding
- перенести папку org.openhab.binding.megad на уровень выше
-  Поменять в  MANIFEST.MF бандл-версию на требуемую, например Bundle-Version: 2.5.0.qualifier 
- поменять версию parent на соответствующую:
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.openhab.binding</groupId>
    <artifactId>pom</artifactId>
    <version>2.5.0-SNAPSHOT</version>
  </parent>

  <properties>
    <bundle.symbolicName>org.openhab.binding.megad</bundle.symbolicName>
    <bundle.namespace>org.openhab.binding.megad</bundle.namespace>
  </properties>

  <artifactId>org.openhab.binding.megad</artifactId>

  <name>MegaD Binding</name>
  <packaging>eclipse-plugin</packaging>
- Добавить модуль в pom.xml в папке bindings: <module>org.openhab.binding.megad</module>
- Выполнить сборку байндинга из корневой папки openhab2-addons с помощью команды:
mvn -DskipChecks=true clean install -f addons/binding/org.openhab.binding.megad

**Comment by Pshatsillo** [comment]
Я готов поправить что нужно, расскажите каким образом? Пошагово. К
сожалению практически полное отсутствие свободного времени не даёт мне
возможности самому вникать, прошу прощения...

вт, 1 янв. 2019 г., 17:00 Fedyanin Timofey notifications@github.com:
