### ISSUE TITLE
Update for openHAB 3

### ISSUE THREAD

**Issue by agsochi** [Pshatsillo/openhab2MegadBinding#22]
Не работает с 3й версией openHAB

**Comment by rayslava** [comment]
Но ведь действительно не работает.
```
(Type=Bridge, Status=UNINITIALIZED (BRIDGE_UNINITIALIZED), Label=Bridge Megad hardware, Bridge=megad:bridge:my)
```
Хотя тот же конфиг на 2.5 работал отлично.
И в логах ничего не пишет про то, что инициализирует bridge.

**Comment by Pshatsillo** [comment]
Вы точно скачиваете биндинг для 3 версии??

скорее всего проблема в том, что megad:bridge изменился на megad:tcp

**Comment by rayslava** [comment]
Да, действительно, проблема была в документации. Спасибо за апдейт.
Правда сейчас всё ещё неправильные примеры в секции про `.items`, но после переключения на `:tcp:` по логам хотя бы стало понятно, что куда вписывать. Всё завелось, спасибо!

**Comment by Pshatsillo** [comment]
Это вам спасибо. Постараюсь привести в порядок документацию. Не хватает времени катастрофически
