### ISSUE TITLE
Предложение по унификации расширителей

### ISSUE THREAD

**Issue by FurmanenkoIgor** [Pshatsillo/openhab2MegadBinding#25]
MCP23008/MCP23017 и PCA9685 по своей функциональности расширители.
Предлагаю модифицировать билд с учетом унификации имеющихся и будущих расширителей по принципу именования сущностей и переменных по прицепу extender<ТипРасширителя>, например:
extPCA9685dimmer
extMCP230XXout
thing-extenderPCA9685.xml
thing-extenderMC230XX.xml
extenderPCA9685Bridge
extenderMC230XXBridge
MegaDBridgeExtenderPCA9685Handler
MegaDBridgeExtenderMCP230XXHandler
extenderPCA9685HandlerMap
extenderMCP230XXHandlerMap
и так далее..

**Comment by Pshatsillo** [comment]
Согласен
