### ISSUE TITLE
Предложение по унификации каналов Things

### ISSUE THREAD

**Issue by FurmanenkoIgor** [Pshatsillo/openhab2MegadBinding#27]
Так как работа с каналами Things ведется на основе сущностей thing-<*>.xml, MegaD<*>Handler.java,
предлагаю упразднить уникальные канал, такие как extout extin и использовать унифицированные, такие как out, in, dimmer

**Comment by Pshatsillo** [comment]
Да, поддерживаю. По большому счёту там много чего нужно оптимизировать.
