### ISSUE TITLE
Fix code quality checks for 2.5.0

### ISSUE THREAD

**Issue by tfedyanin** [Pshatsillo/openhab2MegadBinding#3]
Ошибки касаются только метаинформации, сборка проходит с -DskipChecks=true. Однако данные нестыковки могут привести к скрытым проблемам, которые будет тяжело отладить.
`[INFO] Individual report appended to summary report.
[ERROR] Code Analysis Tool has found:
 18 error(s)!
 12 warning(s)
 95 info(s)
[ERROR] .binding.megad/build.properties:[0]
about.html file must be added to the bin.includes property
[WARNING] .binding.megad/ESH-INF/binding/binding.xml:[3]
There were whitespace characters used for indentation. Please use tab characters instead
[WARNING] .binding.megad/ESH-INF/thing/thing-types.xml:[163]
There were whitespace characters used for indentation. Please use tab characters instead
[ERROR] .binding.megad/META-INF/MANIFEST.MF:[0]
The package org.openhab.binding.megad.i2c should be marked as "internal" if it is not exported.
[WARNING] .binding.megad/META-INF/MANIFEST.MF:[7]
Unexpected "JavaSE-1.7", only allowed options: [JavaSE-1.8]
[WARNING] .binding.megad/META-INF/MANIFEST.MF:[9]
Every bundle should have optional Import-Package dependency to org.eclipse.jdt.annotation.
[WARNING] .binding.megad/META-INF/MANIFEST.MF:[10]
The version of the package org.apache.commons.codec.binary should not be specified
[WARNING] .binding.megad/META-INF/MANIFEST.MF:[11]
The version of the package org.apache.commons.lang should not be specified
[WARNING] .binding.megad/META-INF/MANIFEST.MF:[19]
The exported package `org.openhab.binding.megad.handler` is not imported
[WARNING] .binding.megad/META-INF/MANIFEST.MF:[19]
The exported package `org.openhab.binding.megad` is not imported
[WARNING] .binding.megad/OSGI-INF/MegaDHandlerFactory.xml:[4]
There were whitespace characters used for indentation. Please use tab characters instead
[ERROR] org.openhab.binding.megad.handler.MegaDBridgeHandler.java:[1]
Header is missing
[WARNING] org.openhab.binding.megad.handler.MegaDBridgeHandler.java:[146]
For periodically executed jobs that do not require a fixed rate scheduleWithFixedDelay should be preferred over scheduleAtFixedRate.
[ERROR] org.openhab.binding.megad.handler.MegaDBridgeHandler.java:[183]
Avoid printStackTrace(); use a logger call instead.
[ERROR] org.openhab.binding.megad.handler.MegaDBridgeHandler.java:[357]
Avoid printStackTrace(); use a logger call instead.
[ERROR] org.openhab.binding.megad.handler.MegaDHandler.java:[2]
Header line doesn't match pattern ^ \* Copyright \(c\) 2010-2018 by the respective copyright holders\.$
[ERROR] org.openhab.binding.megad.handler.MegaDHandler.java:[131]
Avoid printStackTrace(); use a logger call instead.
[ERROR] org.openhab.binding.megad.handler.MegaDHandler.java:[134]
Avoid printStackTrace(); use a logger call instead.
[ERROR] org.openhab.binding.megad.MegaDBindingConfiguration.java:[1]
Header is missing
[ERROR] org.openhab.binding.megad.MegaDBindingConfiguration.java:[3]
An author tag is missing
[WARNING] org.openhab.binding.megad.MegaDBindingConfiguration.java:[3]
Missing Javadoc comment.
[ERROR] org.openhab.binding.megad.i2c.I2C.java:[1]
Header is missing
[ERROR] org.openhab.binding.megad.i2c.I2C.java:[16]
An author tag is missing
[WARNING] org.openhab.binding.megad.i2c.I2C.java:[16]
Missing Javadoc comment.
[ERROR] org.openhab.binding.megad.i2c.I2C.java:[92]
Avoid printStackTrace(); use a logger call instead.
[ERROR] org.openhab.binding.megad.i2c.I2C.java:[95]
Avoid printStackTrace(); use a logger call instead.
[ERROR] org.openhab.binding.megad.internal.MegaDHandlerFactory.java:[2]
Header line doesn't match pattern ^ \* Copyright \(c\) 2010-2018 by the respective copyright holders\.$
[ERROR] org.openhab.binding.megad.MegaDBindingConstants.java:[2]
Header line doesn't match pattern ^ \* Copyright \(c\) 2010-2018 by the respective copyright holders\.$
[ERROR] .binding.megad/about.html:[0]
Missing about.html file.
[ERROR] .binding.megad/META-INF/MANIFEST.MF:[18]
A good approach is to use OSGI-INF/*.xml instead of including the services metadata files separately or using common wildcard.`

**Comment by Pshatsillo** [comment]
Расскажите пожалуйста, эти ошибки возникают при сборке через mvn?
