### ISSUE TITLE
Feature request: add channels Click, DoubleClick & Hold

### ISSUE THREAD

**Issue by agsochi** [Pshatsillo/openhab2MegadBinding#6]
С - Click Mode

В режиме Click Mode:
При однократном нажатии на выключатель на сервер передается параметр click=1
Пример: /md.php?pt=0&click=1&cnt=1
При двойном нажатии (двойной клик) на сервер передается параметр click=2
Пример: /md.php?pt=0&click=2&cnt=2
При удержатии клавиши как и в других режимах передается параметр m=2
Пример: /md.php?pt=0&m=2&cnt=3
После отпускания клавиши после длительного нажатия передается параметр m=1 (как в режиме P&R)
Пример: /md.php?pt=0&m=1&cnt=3

**Comment by Pshatsillo** [comment]
Все эти режимы реализуются уже имеющимся функционалом. Какой смысл тащить в
биндинг то, что реализуется правилами самого сервера?

пт, 1 мар. 2019 г. в 10:53, agsochi <notifications@github.com>:

**Comment by agsochi** [comment]
На мой взгляд биндинг должен обрабатывать все запросы, что отдает контроллер. 
Конкретно у меня много кнопок с двойным назначением и писать еще и обработку нажатий мне сложно. 
Это же так удобно - получить готовое событие в openHab.

**Comment by agsochi** [comment]
у Intrahouse есть обработка этих нажатий:
![изображение](https://user-images.githubusercontent.com/2944079/55956943-cb174000-5c6d-11e9-89bb-e12d0fcf6dc6.png)
