### ISSUE TITLE
Add support of DS2413 mode

### ISSUE THREAD

**Issue by kiberxx** [Pshatsillo/openhab2MegadBinding#9]
Currently, the binding doesn't allow to create things based on DS2413.
It's supposed to have additional parameters:

1. Channel (A/B)
2. Address (physical address of micro scheme)

Or perhaps, it's better to create a new thing.

The binding should support next calls for MegaD:
To enable/disable channels:
http://192.168.0.14/sec/?cmd=7A:0
http://192.168.0.14/sec/?cmd=7A:1
http://192.168.0.14/sec/?cmd=7B:0
http://192.168.0.14/sec/?cmd=7B:1
The same with the specified address when several devices are connected to the bus:
http://192.168.0.14/sec/?cmd=7A:0&&addr=57b139000000 

Please find "DS2413" in the article for a detailed description:
https://www.ab-log.ru/smart-house/ethernet/megad-2561

P.S. I can create pull-request with the requested functionality.

**Comment by Pshatsillo** [comment]
Если у Вас есть возможность создать эту функцию - прекрасно, единственная просьба - сделать это в рамках параметров, а не отдельно канала

**Comment by kiberxx** [comment]
ОК, накидаю что нибудь. А есть како нибудь способ с вами как-то более интеракивно общаться, telegram, skype, watsapp?

**Comment by Pshatsillo** [comment]
Да, есть в целом всё:) telegram: @Petrosts

вт, 28 мая 2019 г., 11:44 Viacheslav <notifications@github.com>:
